"use client";

import { useCallback, useEffect, useState } from "react";
import GameClient from "./game-client";
import type { GameHistoryDetail, GameHistorySummary, RoomDetail, RoomSummary, SessionProfile } from "@/matchmaking/types";

const ROOMS_CACHE="wa_rooms_cache_v1"; const HISTORY_CACHE="wa_history_cache_v1";
async function json<T>(url:string,init?:RequestInit){const response=await fetch(url,{cache:"no-store",...init});const body=await response.json();if(!response.ok)throw new Error(body.error??"요청 실패");return body as T}

function GameLedgerOverlay({history,detail,nextCursor,onMore,onOpen,onBack,onClose}:{history:GameHistorySummary[];detail:GameHistoryDetail|null;nextCursor:string|null;onMore:()=>void;onOpen:(id:string)=>void;onBack:()=>void;onClose:()=>void}){
  return <div className="history-drawer in-game-ledger"><header><div><small>PUBLIC LEDGER</small><h2>전체 게임 기록</h2></div><button onClick={onClose}>×</button></header>{detail?<div className="ledger-detail"><button onClick={onBack}>← 목록</button><h3>{detail.roomName}</h3><p>{new Date(detail.endedAt).toLocaleString("ko-KR")} · {detail.rounds} 라운드</p><div className="winner">우승 {detail.winnerNickname??"무승부"}</div><h4>참가자</h4><p>{detail.playerNicknames.join(" · ")}</p><h4>요약</h4><pre>{JSON.stringify(detail.summary,null,2)}</pre><h4>전체 장부</h4><pre>{JSON.stringify(detail.ledger,null,2)}</pre></div>:<div className="history-list">{history.length===0?<p>완료된 게임이 아직 없습니다.</p>:history.map((item)=><button key={item.id} onClick={()=>onOpen(item.id)}><div><strong>{item.roomName}</strong><small>{item.playerNicknames.join(" · ")}</small></div><span><b>{item.winnerNickname??"무승부"}</b><small>{new Date(item.endedAt).toLocaleString("ko-KR")}</small></span></button>)}{nextCursor&&<button className="load-more" onClick={onMore}>이전 기록 더 불러오기</button>}</div>}</div>
}

export default function AppShell(){
  const [profile,setProfile]=useState<SessionProfile|null>(null); const [nickname,setNickname]=useState("");
  const [rooms,setRooms]=useState<RoomSummary[]>([]); const [history,setHistory]=useState<GameHistorySummary[]>([]);
  const [activeRoomId,setActiveRoomId]=useState<string|null>(null); const [room,setRoom]=useState<RoomDetail|null>(null);
  const [historyOpen,setHistoryOpen]=useState(false); const [historyDetail,setHistoryDetail]=useState<GameHistoryDetail|null>(null);
  const [historyCursor,setHistoryCursor]=useState<string|null>(null);
  const [creating,setCreating]=useState(false); const [roomName,setRoomName]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [syncedAt,setSyncedAt]=useState<string|null>(null);

  const refreshLobby=useCallback(async()=>{try{const [roomData,historyData]=await Promise.all([json<{rooms:RoomSummary[];serverNow:string}>("/api/rooms"),json<{history:GameHistorySummary[];nextCursor:string|null;serverNow:string}>("/api/history")]);setRooms(roomData.rooms);setHistory(historyData.history);setHistoryCursor(historyData.nextCursor);setSyncedAt(roomData.serverNow);localStorage.setItem(ROOMS_CACHE,JSON.stringify(roomData.rooms));localStorage.setItem(HISTORY_CACHE,JSON.stringify(historyData.history));}catch{setError("최신 로비 정보를 가져오지 못해 캐시를 표시합니다.")}},[]);
  const refreshRoom=useCallback(async(id:string)=>{try{const body=await json<{room:RoomDetail;serverNow:string}>(`/api/rooms/${id}`);setRoom(body.room);setSyncedAt(body.serverNow);if(body.room.status==="FINISHED"){setActiveRoomId(null);setRoom(null);void refreshLobby()}}catch{setError("방 정보를 갱신하지 못했습니다.")}},[refreshLobby]);

  useEffect(()=>{let cancelled=false;Promise.resolve().then(()=>{try{const cachedRooms=localStorage.getItem(ROOMS_CACHE);const cachedHistory=localStorage.getItem(HISTORY_CACHE);if(!cancelled&&cachedRooms)setRooms(JSON.parse(cachedRooms));if(!cancelled&&cachedHistory)setHistory(JSON.parse(cachedHistory))}catch{}});void json<{profile:SessionProfile}>("/api/session").then((body)=>{if(!cancelled){setProfile(body.profile);setNickname(body.profile.nickname??"");setActiveRoomId(body.profile.activeRoomId)}}).catch(()=>setError("세션을 발급하지 못했습니다."));queueMicrotask(()=>void refreshLobby());return()=>{cancelled=true}},[refreshLobby]);
  useEffect(()=>{if(activeRoomId)return;const timer=window.setInterval(()=>{if(document.visibilityState==="visible")void refreshLobby()},4000);return()=>window.clearInterval(timer)},[activeRoomId,refreshLobby]);
  useEffect(()=>{if(!activeRoomId)return;queueMicrotask(()=>void refreshRoom(activeRoomId));const timer=window.setInterval(()=>void refreshRoom(activeRoomId),1500);return()=>window.clearInterval(timer)},[activeRoomId,refreshRoom]);

  async function saveNickname(event:React.FormEvent){event.preventDefault();setBusy(true);setError(null);try{const body=await json<{profile:SessionProfile}>("/api/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({nickname})});setProfile(body.profile)}catch(e){setError(e instanceof Error?e.message:"닉네임 저장 실패")}finally{setBusy(false)}}
  async function create(){if(!roomName.trim())return;setBusy(true);try{const body=await json<{roomId:string}>("/api/rooms",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:roomName})});setCreating(false);setRoomName("");setActiveRoomId(body.roomId)}catch(e){setError(e instanceof Error?e.message:"방 생성 실패")}finally{setBusy(false)}}
  async function roomAction(payload:Record<string,unknown>){if(!activeRoomId)return;setBusy(true);try{const body=await json<{room?:RoomDetail}>(`/api/rooms/${activeRoomId}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(payload.type==="LEAVE"){setActiveRoomId(null);setRoom(null);void refreshLobby()}else if(body.room)setRoom(body.room)}catch(e){setError(e instanceof Error?e.message:"방 명령 실패")}finally{setBusy(false)}}
  async function openHistory(id:string){setHistoryOpen(true);setHistoryDetail(null);try{const body=await json<{history:GameHistoryDetail}>(`/api/history/${id}`);setHistoryDetail(body.history)}catch{setError("상세 장부를 불러오지 못했습니다.")}}
  async function loadMoreHistory(){if(!historyCursor)return;try{const body=await json<{history:GameHistorySummary[];nextCursor:string|null}>(`/api/history?cursor=${encodeURIComponent(historyCursor)}`);setHistory((current)=>[...current,...body.history.filter((item)=>!current.some((old)=>old.id===item.id))]);setHistoryCursor(body.nextCursor)}catch{setError("이전 게임 기록을 불러오지 못했습니다.")}}

  if(!profile||!profile.nickname)return <div className="portal-bg"><form className="nickname-card" onSubmit={saveNickname}><span className="brand-mark">WA</span><small>ANONYMOUS SESSION</small><h1>전장 이름을 정하세요</h1><p>로그인은 없습니다. 이 브라우저 세션이 유지되는 동안 닉네임과 게임 기록이 연결됩니다. 닉네임 중복은 허용됩니다.</p><input autoFocus maxLength={16} value={nickname} onChange={(e)=>setNickname(e.target.value)} placeholder="닉네임 1~16자"/><button disabled={busy||!nickname.trim()}>세션 시작</button>{error&&<em>{error}</em>}</form></div>;
  if(room?.status==="STARTED")return <div className="game-mode-wrapper"><GameClient gameKey={room.gameId??room.id} roomName={room.name}/><button className="floating-ledger" onClick={()=>{setHistoryOpen(true);void refreshLobby()}}>☰ 게임 기록</button>{historyOpen&&<GameLedgerOverlay history={history} detail={historyDetail} nextCursor={historyCursor} onMore={()=>void loadMoreHistory()} onOpen={(id)=>void openHistory(id)} onBack={()=>setHistoryDetail(null)} onClose={()=>{setHistoryOpen(false);setHistoryDetail(null)}}/>}</div>;

  return <main className="portal-bg lobby-shell">
    <header className="portal-header"><div className="brand"><span className="brand-mark">WA</span><div><strong>WEB AUTOBATTLER</strong><small>ONLINE LOBBY</small></div></div><nav><button onClick={()=>{setHistoryOpen(true);void refreshLobby()}}>전체 게임 기록 <b>{history.length}</b></button><span className="session-badge"><i/> {profile.nickname}<small>{profile.id.slice(0,8)}</small></span></nav></header>
    {error&&<button className="toast" onClick={()=>setError(null)}>{error} ×</button>}
    {activeRoomId&&room?<section className="room-screen"><button className="back-link" onClick={()=>void roomAction({type:"LEAVE"})}>← {room.viewerIsHost?"방 닫기":"방 나가기"}</button><div className="room-heading"><div><small>WAITING ROOM · {room.id.slice(0,8)}</small><h1>{room.name}</h1><p>방장 {room.hostNickname} · 서버 상태 #{room.version}</p></div><div className="room-count"><b>{room.playerCount}</b><span>/ {room.maxPlayers}</span></div></div><div className="seat-grid">{Array.from({length:room.maxPlayers},(_,seat)=>{const player=room.players.find((p)=>p.seat===seat);return <div className={`seat ${player?"occupied":""}`} key={seat}><span className="seat-number">{seat+1}</span>{player?<><div className="avatar">{player.nickname.slice(0,1)}</div><strong>{player.nickname}{player.sessionId===profile.id&&" (나)"}</strong><small>{player.isHost?"방장":player.ready?"READY":"대기 중"}</small><i className={player.ready?"ready":""}/></>:<><div className="empty-seat">+</div><small>빈 자리</small></>}</div>})}</div><div className="room-actions">{!room.viewerIsMember?<button className="primary" disabled={busy||room.playerCount>=room.maxPlayers} onClick={()=>void roomAction({type:"JOIN"})}>방 참가</button>:room.viewerIsHost?<button className="primary" disabled={busy||room.playerCount<2||room.players.some((p)=>!p.isHost&&!p.ready)} onClick={()=>void roomAction({type:"START"})}>게임 시작</button>:<button className={`primary ${room.players.find((p)=>p.sessionId===profile.id)?.ready?"ready-button":""}`} disabled={busy} onClick={()=>void roomAction({type:"READY",ready:!room.players.find((p)=>p.sessionId===profile.id)?.ready})}>{room.players.find((p)=>p.sessionId===profile.id)?.ready?"READY 취소":"READY"}</button>}<p>{room.playerCount<2?"최소 2명이 필요합니다.":room.players.some((p)=>!p.isHost&&!p.ready)?"모든 참가자가 READY 해야 시작할 수 있습니다.":"시작할 준비가 되었습니다."}</p></div></section>
    :<section className="lobby-content"><div className="lobby-title"><div><small>PUBLIC MATCHMAKING</small><h1>온라인 게임 방</h1><p>캐시된 목록을 즉시 표시하고 서버 데이터로 백그라운드 갱신합니다.</p></div><div><span>{syncedAt?`동기화 ${new Date(syncedAt).toLocaleTimeString("ko-KR")}`:"동기화 중"}</span><button onClick={()=>void refreshLobby()}>↻ 새로고침</button><button className="create-button" onClick={()=>setCreating(true)}>＋ 방 만들기</button></div></div><div className="room-list">{rooms.length===0?<div className="empty-lobby"><b>대기 중인 방이 없습니다</b><p>첫 번째 게임 방을 만들어 보세요.</p></div>:rooms.map((item)=><button className="room-card" key={item.id} onClick={()=>setActiveRoomId(item.id)}><span className="room-icon">◇</span><div><strong>{item.name}</strong><small>방장 {item.hostNickname} · {new Date(item.createdAt).toLocaleTimeString("ko-KR")}</small></div><em>{item.playerCount}/{item.maxPlayers}</em><b>입장 →</b></button>)}</div></section>}
    {creating&&<div className="modal-backdrop"><form className="create-modal" onSubmit={(e)=>{e.preventDefault();void create()}}><h2>새 게임 방</h2><p>방장은 참가자들이 준비되면 게임을 시작할 수 있습니다.</p><input autoFocus maxLength={30} value={roomName} onChange={(e)=>setRoomName(e.target.value)} placeholder={`${profile.nickname}의 게임`}/><div><button type="button" onClick={()=>setCreating(false)}>취소</button><button className="primary" disabled={busy||!roomName.trim()}>생성</button></div></form></div>}
    {historyOpen&&<div className="history-drawer"><header><div><small>PUBLIC LEDGER</small><h2>전체 게임 기록</h2></div><button onClick={()=>{setHistoryOpen(false);setHistoryDetail(null)}}>×</button></header>{historyDetail?<div className="ledger-detail"><button onClick={()=>setHistoryDetail(null)}>← 목록</button><h3>{historyDetail.roomName}</h3><p>{new Date(historyDetail.endedAt).toLocaleString("ko-KR")} · {historyDetail.rounds} 라운드</p><div className="winner">우승 {historyDetail.winnerNickname??"무승부"}</div><h4>참가자</h4><p>{historyDetail.playerNicknames.join(" · ")}</p><h4>요약</h4><pre>{JSON.stringify(historyDetail.summary,null,2)}</pre><h4>전체 장부</h4><pre>{JSON.stringify(historyDetail.ledger,null,2)}</pre></div>:<div className="history-list">{history.length===0?<p>완료된 게임이 아직 없습니다.</p>:history.map((item)=><button key={item.id} onClick={()=>void openHistory(item.id)}><div><strong>{item.roomName}</strong><small>{item.playerNicknames.join(" · ")}</small></div><span><b>{item.winnerNickname??"무승부"}</b><small>{new Date(item.endedAt).toLocaleString("ko-KR")}</small></span></button>)}{historyCursor&&<button className="load-more" onClick={()=>void loadMoreHistory()}>이전 기록 더 불러오기</button>}</div>}</div>}
  </main>;
}
